import React from "react";
/** Type */
import type { Metadata } from "next";
import { Llama } from "@/utils/type";
/** Style */
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<Llama.Layout> = ({ children }) => {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
