import React from "react";
/** Type */
import type { Metadata } from "next";
import { Llama } from "@/utils/type";
/** Style */
import "@/app/globals.css";
/** Component */
import Footer from "@/components/Footer";
/** Provider */
import QueryProvider from "@/provider/QueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<Llama.Layout> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <main className="border border-black min-h-[calc(100vh-4rem)]">{children}</main>

          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
};

export default RootLayout;
